import { mapAllegationToStatutes, resolveJurisdiction } from '@/legal/data';
import { buildLegalPromptPayload } from '@/services/openaiPrompts';
import { type AllegationSummary, type JurisdictionInfo, type LegalSummaryResponse } from '@/types/legal';
import { isOpenAIConfigured } from './openaiClient';
import OpenAI from 'openai';

const client = isOpenAIConfigured
  ? new OpenAI({
      apiKey: import.meta.env.VITE_OPENAI_API_KEY,
      dangerouslyAllowBrowser: true,
    })
  : null;

const safeJsonParse = (content: string): LegalSummaryResponse | null => {
  const start = content.indexOf('{');
  const end = content.lastIndexOf('}');
  if (start === -1 || end === -1) return null;
  try {
    return JSON.parse(content.slice(start, end + 1));
  } catch {
    return null;
  }
};

const ensureStatutes = (allegation: AllegationSummary, jurisdiction: JurisdictionInfo): AllegationSummary => {
  const statutes =
    allegation.statutes?.length && allegation.statutes[0]?.link
      ? allegation.statutes
      : mapAllegationToStatutes(allegation.type, jurisdiction);

  const summary =
    allegation.summary && allegation.summary.length > 0
      ? allegation.summary
      : `${allegation.raw} This reflects ${allegation.type}. See applicable law: ${statutes
          .map((s) => `${s.label} (${s.link})`)
          .join('; ')}.`;

  return { ...allegation, statutes, summary };
};

export const generateLegalSummary = async (
  narrative: string,
  jurisdictionInput?: string
): Promise<LegalSummaryResponse> => {
  if (!client) {
    throw new Error('OpenAI API key not configured. Set VITE_OPENAI_API_KEY to enable legal analysis.');
  }

  const jurisdiction = resolveJurisdiction(jurisdictionInput);
  const promptPayload = buildLegalPromptPayload(narrative, jurisdiction);

  const response = await client.chat.completions.create({
    model: 'gpt-4o-mini',
    temperature: 0.2,
    response_format: { type: 'json_object' },
    messages: [
      {
        role: 'system',
        content:
          'You are a legal information assistant. You extract allegations, classify behaviours, map to statutes, and produce neutral court-ready summaries with hyperlinks. Do not give legal advice.',
      },
      { role: 'user', content: JSON.stringify(promptPayload) },
    ],
  });

  const content = response.choices[0]?.message?.content ?? '';
  const parsed = safeJsonParse(content) ?? { allegations: [] };

  const allegations = (parsed.allegations ?? []).map((allegation) =>
    ensureStatutes(
      {
        raw: allegation.raw ?? '',
        type: allegation.type ?? 'unclassified',
        statutes: allegation.statutes ?? [],
        summary: allegation.summary ?? '',
      },
      jurisdiction
    )
  );

  return {
    allegations,
    jurisdiction,
    generatedAt: new Date().toISOString(),
  };
};

export const buildMarkdownSummary = (incident: AllegationSummary, j: JurisdictionInfo): string => {
  const statutes = incident.statutes
    .map((s) => `- **${s.label}**\n  ${s.link}`)
    .join('\n');

  return `
# **${incident.type.toUpperCase()} Incident**
**Jurisdiction:** ${j.region}, ${j.country}  
**Generated:** ${new Date().toISOString()}

---

## **Summary**
${incident.summary}

---

## **Legal References**
${statutes}

---

_This summary is generated by the CustodyBuddy Incident Documentation System and is not legal advice._
`;
};
